package com.maxminmajcdg.measures;

public enum Measure {
    PARTISAN_FAIRNESS,
    COMPACTNESS,
    EFFICIENCY_GAP,
    POPULATION_EQUALITY,
    COMPETITIVENESS,
    GERRYMANDER_REPUBLICAN,
    POPULATION_HOMOGENEITY,
    GERRYMANDER_DEMOCRAT
}
